version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.1-debian-11-r108'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.2.3-debian-11-r68'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=32768000
      - KAFKA_CFG_MAX_REQUEST_SIZE=32768000
      - KAFKA_CFG_MESSAGE_MAX_BYTES=32000000
    depends_on:
      - zookeeper
